### ISSUE TITLE
[BUG] Users who aren't the first to join an editing session can't submit words

### ISSUE THREAD

**Issue by wfan19** [wfan19/skribbl_lister_client#1]
When a user who wasn't the first to join a session tries to submit a word, the server is unable to add the word to the db.

Bug log:
```
(node:22820) UnhandledPromiseRejectionWarning: VersionError: No matching document found for id "5ec620f3695c8925cc2c4e92" version 18 modifiedPaths "entries"
    at VersionError.MongooseError [as constructor] (/home/bf01/Documents/Code/skribbl_lister_client/server/node_modules/mongoose/lib/error/mongooseError.js:10:11)
    at new VersionError (/home/bf01/Documents/Code/skribbl_lister_client/server/node_modules/mongoose/lib/error/version.js:18:17)
    at generateVersionError (/home/bf01/Documents/Code/skribbl_lister_client/server/node_modules/mongoose/lib/model.js:414:10)
    at model.Model.save (/home/bf01/Documents/Code/skribbl_lister_client/server/node_modules/mongoose/lib/model.js:469:28)
    at model.List.methods.addEntry (/home/bf01/Documents/Code/skribbl_lister_client/server/models/List.js:52:15)
    at Socket.addEntry (/home/bf01/Documents/Code/skribbl_lister_client/server/socket/RoomManager.js:46:50)
    at Socket.emit (events.js:310:20)
    at /home/bf01/Documents/Code/skribbl_lister_client/server/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:22820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

```

**Comment by wfan19** [comment]
Resolved
